import Head from 'next/head'
import Footer from './Footer'
import Header from './Header'

const PageShell = ({ name, children }) => {
  const title = `Kookie - ${name}`

  return (
    <>
      <Head>
        <title>{title}</title>
        {/* TODO: SEO */}
        {/* TODO: The Open Graph protocol */}
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header name={name} />

      <main className="py-5">
        <div className="container">
          <div>
            {children}
          </div>
        </div>
      </main>

      <Footer />
    </>
  )
}

export default PageShell